### ISSUE TITLE
Is there a way to use two DCSBIOSOutputs in a formula in the DCSBIOSDecoder on a Stream Deck Button?

### ISSUE THREAD

**Issue by jacobdeane** [jdahlblom/DCSFlightpanels#141]
Firstly, let me say thank you for an amazing utility!

I'm trying to create the ACM panel from the F-14B.

I have created a button that can toggle the GUN RATE, and indicate the current rate. I have made graphics that shows HIGH/LOW and illuminates HIGH or LOW as required. I can get it to work using one of the outputs, for example, I pick `PLT_GUN_RATE_HIGH` and if it ==1 illuminate 'HIGH' and if not illuminate 'LOW'.

![gun_rate_HIGH](https://user-images.githubusercontent.com/18046053/133505721-a17eb87e-4010-4a6d-8596-949e187afe87.png) ![gun_rate_LOW](https://user-images.githubusercontent.com/18046053/133505809-2ae7cb8a-b001-48ea-8222-0b25ba8b1a16.png)

It would be really cool if there was a way to combine both the `PLT_GUN_RATE_HIGH `& `PLT_GUN_RATE_LOW `outputs and use a formula such as `PLT_GUN_RATE_LOW*2+PLT_GUN_RATE_HIGH` to give me 4 values (0,1,2 or 3) for each combination of the lights being on or off, that way with power off, both indicators are unlit and with the BIT function, both indicators would be lit.

Is there a way to do this?

**Comment by jdahlblom** [comment]
No it isn't possible in DCSFP. I would suggest that this be made in DCS-BIOS, this way not only DCSFP users but also pit builders could use it.

**Comment by WarLord211** [comment]
in bios are readout for the lights.

**Comment by jdahlblom** [comment]
@WarLord211 so what he needs it already in DCS-BIOS? If so then I'll close this.

**Comment by jdahlblom** [comment]
Or rather I'll close this regardless as it isn't possible in DCSFP, it won't get supported at this stage.

**Comment by jdahlblom** [comment]
Check latest release 4.4.39 and see if you get it working. Please report back. Thanks.

**Comment by jacobdeane** [comment]
@jdahlblom This is perfect, exactly what I was looking for! Thank you so much!
