### ISSUE TITLE
No data from DCS-Bios

### ISSUE THREAD

**Issue by tegami-lpr** [jdahlblom/DCSFlightpanels#142]
Under Windows 10  build 19043.1237 with .Net Framework 4.8.04084 DCSFlightpanels is started, but not receiving data from DCS.
Quick debugging showed that function [ReceiveDataUdp()](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/d35cc85dd2be45070d222ea0001847a16dd776cd/Source/DCS-BIOS/DCSBIOS.cs#L123) never called.
After changing [this line](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/d35cc85dd2be45070d222ea0001847a16dd776cd/Source/DCS-BIOS/DCSBIOS.cs#L166) to ```_dcsbiosListeningThread = new Thread(new ThreadStart(ReceiveDataUdp));```
receiving started working.

**Comment by jdahlblom** [comment]
OK, why would ThreadStart make it work? Can you elaborate?
I can't see any info showing why `_dcsbiosListeningThread = new Thread(ReceiveDataUdp);` shouldn't work.

**Comment by jdahlblom** [comment]
I added this change to both master and development .

**Comment by tegami-lpr** [comment]
First of all, I should regret this quick hack. I fixed it for myself and didn't dig deeper... It's because I'm not real C# developer. :)

Your's previous code is valid. My fix was based on quick look to MSDN docs without looking to Note sections... :(

As I understand problem is all about execution timing. Look:
1) [_dcsbiosListeningThread = new Thread(ReceiveDataUdp);](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/89f148eb56764bc7924fc0a8e8fedd0d73aed8a3/Source/DCS-BIOS/DCSBIOS.cs#L166) - thread created with _ReceiveDataUdp()_ as execution delegate.
2) [_dcsbiosListeningThread.Start();](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/89f148eb56764bc7924fc0a8e8fedd0d73aed8a3/Source/DCS-BIOS/DCSBIOS.cs#L167) - thread started and began execute ReceiveDataUdp() going to  [while (_isRunning)](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/89f148eb56764bc7924fc0a8e8fedd0d73aed8a3/Source/DCS-BIOS/DCSBIOS.cs#L127) where __isRunning_ is **False**.
3) [_isRunning = true;](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/89f148eb56764bc7924fc0a8e8fedd0d73aed8a3/Source/DCS-BIOS/DCSBIOS.cs#L170) _isRunning setted to True. But execution of _ReceiveDataUdp()_ from step 2 is already ended!

If code will be rearranged like this:
```
_dcsbiosListeningThread = new Thread(ReceiveDataUdp);
_dcsProtocolParser.Startup();
_isRunning = true;
_dcsbiosListeningThread.Start();
```
all be fine.

**Comment by jdahlblom** [comment]
Thanks for this find. I've modified as you suggested. This should explain why DCS-BIOS sometimes doesn't kick in.

**Comment by jdahlblom** [comment]
Damn it. Now I have Debug working but Release doesn't get DCS-BIOS data. I've had problem recently with Release build not working, found one optimization bug but this I can't explain atm.

**Comment by tegami-lpr** [comment]
Yep, I see...
Ok, let's dig it's out...

**Comment by jdahlblom** [comment]
I have had problems which I never found out what was, hanging problems. I wonder whether it is the same now. One reason DCSFP restarts after choosing a new module is just that, I had hanging problems.

**Comment by tegami-lpr** [comment]
I build it as Release and all work without errors. But I think lines [there](https://github.com/DCSFlightpanels/DCSFlightpanels/blob/d734e7378628590caf4a31a07bae668cf594a9a3/Source/DCS-BIOS/DCSBIOSProtocolParser.cs#L90) must be rearanged too, because it will work as intended only right after class instantination.

**Comment by jdahlblom** [comment]
Yes, true. I already re-arranged them. Now I found out why the cog-wheel isn't spinning in the UI. Because there are no DCS-BIOS control objects used in the profile. Since DCS-BIOS isn't used in a blank profile then the DCSBIOSProtocolParser doesn't cause an event. I have to fix that.

**Comment by jdahlblom** [comment]
Because the DCSBIOSProtocolParser  doesn't broadcast (create events) unless there are someone actually listening for DCS-BIOS data. (some DCS-BIOS control has been assigned to a e.g. Stream Deck display)

**Comment by tegami-lpr** [comment]
Yes, I noticed this too, but I thinked it is as must be. :)
Ok, I think issue may be closed now. :)
