### ISSUE TITLE
Mi-8MT module problem (PZ69 + R863 radio)

### ISSUE THREAD

**Issue by dslawek** [jdahlblom/DCSFlightpanels#145]
For R863 radio (COM1), after pressing ACT/STBY active frequency of 100kHz is not correctly transmitted to standby LCD.
Example:
ACTIVE: 127.50 STANDBY: 128.00
after press ACT/STBY
ACTIVE: 128.00 STANDBY: 127.05 (STANDBY .50 > 0.05)

Example video: [https://youtu.be/oz_jyd3MMjI](https://youtu.be/oz_jyd3MMjI)

**Comment by jdahlblom** [comment]
I see there has been changes to DCS-BIOS Mi-8MT.lua.

**Comment by jdahlblom** [comment]
Exactly this dial (R863) has been problematic since start. I've changed it back to how it was before (commit 69ccee0b2793b588f12271dcb9fe39720846831f) so it shows the correct value.

**Comment by jdahlblom** [comment]
Official DCS and latest DCS-BIOS (August).

**Comment by jdahlblom** [comment]
`defineFloat("R863_FREQ1_TUBE", 157, {0, 1}, "Indicator", "R-863, 10MHz Tube")
defineFloat("R863_FREQ2_TUBE", 158, {0, 1}, "Indicator", "R-863, 1MHz Tube")
defineFloat("R863_FREQ3_TUBE", 159, {0, 1}, "Indicator", "R-863, 100KHz Tube")
defineFloat("R863_FREQ4_TUBE", 116, {0, 1}, "Indicator", "R-863, 1KHz Tube")`

but the following does not use same arguments (116 -> 160) :

`defineFixedStepTumb("R863_FREQ1", 38, 3006, 157, 0.01, {0, 0.23}, {-0.1, 0.1}, {"10", "11", "12", "13", "14", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39"}, "R-863", "R-863, 10MHz Rotary Knob")
defineFixedStepTumb("R863_FREQ2", 38, 3007, 158, 0.1, {0, 1}, {-0.1, 0.1}, {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}, "R-863", "R-863, 1MHz Rotary Knob")
defineFixedStepTumb("R863_FREQ3", 38, 3008, 159, 0.1, {0, 1}, {-0.1, 0.1}, {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}, "R-863", "R-863, 100KHz Rotary Knob")
defineFixedStepTumb("R863_FREQ4", 38, 3009, 160, 0.25, {0, 1}, {-0.1, 0.1}, {"00", "25", "50", "75", "00"}, "R-863", "R-863, 1KHz Rotary Knob")`

**Comment by jdahlblom** [comment]
![Screen_210923_211745](https://user-images.githubusercontent.com/10453261/134562179-77a0d968-9ea6-404d-9e10-33e2be46d173.png)
![2021-09-23_211810](https://user-images.githubusercontent.com/10453261/134562189-e43d842b-81b0-44dc-ba22-3273a73a7a74.png)

**Comment by jdahlblom** [comment]
There is something wrong with  the formula. And I used argument 116 for dial 4 in the formula. Didn't get error in dcs.log when changing the argument from 160 to 116.

**Comment by jdahlblom** [comment]
To conclude, there was an error in DCSFP when showing the standby frequency.  
But I have problems syncing, DCS-BIOS crashes. From 127.50 to 108.00 is fine, vice versa and it goes bonkers.
If I remember correctly I switched to using DCS-BIOS strings because there were problems with getting the data and I am reluctant to switch back to reading the dials. This radio has been a constant pain.

EDIT:
I changed back argument value from 160 to 116 for dial 4 so it was "as released" when doing the later test.

**Comment by dslawek** [comment]
Argument 116 is bad for dial4 R-863 (116 = OILS_T_LEFT_ENGINE).

DCS-BIOS\lib\Mi-8MT.lua:
`defineFloat("OILS_T_LEFT_ENGINE", 116, {-0.25, 0.75}, "Indicator", "oils_t_left_engine")`

Argument 160 is correct for dial4 R-863
Mods\aircraft\Mi-8MTV2\Cockpit\Scripts\clickabledata.lua:
`elements["PTR-APP-LVR-SEL4"] = radio_wheel_1( _("R-863, 1kHz Rotary Knob"), devices.R_863, device_commands.Button_9, 166, {-0.1, 0.1},{0,1},{160,{0.0,1.0},2.5}, {-90,90,0})`

**Comment by dslawek** [comment]
I made some small fixes to Mi-8MT.lua (I don't know if it's fully correct, but at least DCS-BIOS doesn't crashes ;-)): [Mi-8MT.lua](https://github.com/dslawek/dcs-bios/blob/master/Scripts/DCS-BIOS/lib/Mi-8MT.lua)

Problem with standby frequency display still exists (change pos. 100kHz to 10kHz). Maybe problem is remembering the old active frequency and not just displaying it.

**Comment by jdahlblom** [comment]
OK try 4.4.19, does it work for you?

**Comment by dslawek** [comment]
Now ACT>STBY works :
ACTIVE: 127.50 STANDBY: 128.00
after press ACT/STBY
ACTIVE: 128.00 STANDBY: 127.50 - **(OK!!!)**

but now the opposite problem has arisen: 
ACTIVE: 128.00 STANDBY: 127.50
after press ACT/STBY
ACTIVE: 127.05 STANDBY: 128.00 - **(ACTIVE: .50 > .05)**

**Comment by jdahlblom** [comment]
Check 4.4.20. Is that OK?

**Comment by dslawek** [comment]
The problem is almost fixed. If the digit in the 100kHz position is greater than 0, it works. Error occurs for XXX.0[257].

Example:
ACTIVE: 100.02 STANDBY: 100.00
after press ACT/STBY
ACTIVE: 100.00 STANDBY: 100.25 - **(STANDBY: .02 > .25)**

Another problem is that it is impossible to set a value below 100 kHz. By turning small knob clockwise, the sequence is:
.00 > **.25 > .50 > .75** > .10 > .12 > .15 ...

and it should be like this:
.00 > **.02 > .05 > .07** > .10 > .12 > .15 ...

**Comment by jdahlblom** [comment]
OK try 4.4.22.

**Comment by dslawek** [comment]
Now works perfectly. 
Thank you for your excellent job!!!

**Comment by dslawek** [comment]
Unfortunately, I found 3 more wrong cases after pressing ACT/STBY (I don't know how I missed them before):
- STANDBY: xxx.02 > ACTIVE: xxx.25
- STANDBY: xxx.05 > ACTIVE: xxx.50
- STANDBY: xxx.07 > ACTIVE: xxx.75

**Comment by jdahlblom** [comment]
Check 4.4.25.

**Comment by dslawek** [comment]
Works. Thx.
