### ISSUE TITLE
Mi-8MT PZ69/R-863 radio frequency range

### ISSUE THREAD

**Issue by dslawek** [jdahlblom/DCSFlightpanels#146]
Currently (Mi-8MT PZ69/R-863) the following frequency ranges can be set:
`100.000 - 149.000, 220.000 - 399.000`
Valid ranges:
`100.000 - 149.975, 220.000 - 399.975`

Any chance to change these ranges? This is not a critical issue, but it would be nice...;-).

**Comment by jdahlblom** [comment]
OK check 4.4.23.

**Comment by dslawek** [comment]
Works. Thank you.!!!
