### ISSUE TITLE
Improvment Mi-8MT (direct change min<>max)

### ISSUE THREAD

**Issue by dslawek** [jdahlblom/DCSFlightpanels#147]
In PZ69 radio for Mi-8MT, when setting the value, it is not possible to directly change between the min and max values (and vice versa).
Missing cases:
- COM1 big knob - R-863 frequency: 399 <> 100
- COM2 big knob - R-863 presets: 1 <> 20
- NAV1 big knob - YaDRO frequency: 20 <> 179
- NAV2 big knob - R-828 presets: 1 <> 10

**Comment by jdahlblom** [comment]
So the preset won't be corrected, they work differently and I don't want to change that. But the manual frequencies now roll over.

**Comment by jdahlblom** [comment]
So check 4.4.24.

**Comment by dslawek** [comment]
Works, but there is one small problem - too much change at min <> max.
- R-863 big knob:
clockwise: 399>101 (should be 399>100)
counterclockwise: 100>398 (should be 100>399)

- YaDRO big knob:
clockwise: 179>21 (should be 179>20)
counterclockwise: 20>178 (should be 20>179)

**Comment by jdahlblom** [comment]
Check 4.4.25.

**Comment by dslawek** [comment]
3 out of 4 cases work. One case still fails:
- YaDRO big knob:
clockwise: 179>21 (should be 179>20)

**Comment by jdahlblom** [comment]
Check 4.4.26.

**Comment by dslawek** [comment]
Works. Thank you.
