### ISSUE TITLE
Mi-8MT - low base sensitivity of knobs

### ISSUE THREAD

**Issue by dslawek** [jdahlblom/DCSFlightpanels#149]
For all options, except for manual frequency (R-863, YaDRO) and volume setting, the base sensitivity of the knobs is too low.
Example: for the set 'Frequency Knobs sensitivity' = 0, changing the R-863 (presets) channel by 1 requires 4 encoder steps.

**Comment by jdahlblom** [comment]
Please be specific. Which ones are too slow in changing. All presets?

**Comment by jdahlblom** [comment]
Check 4.4.28.

**Comment by dslawek** [comment]
Now it's better: a 1 step change requires 2 encoder steps (previously 4 encoder steps were required).
In my opinion it should be 1:1.

**Comment by jdahlblom** [comment]
Take it or leave it mate.

**Comment by dslawek** [comment]
OK - 1:2 is enough. Thx.

**Comment by jdahlblom** [comment]
There is no skipping of the dial now. Everything time a signal comes in a frequency change is sent to DCS. 1:2 is either because the actual bumps in the dial is not the same as numer of signals or there is some other delays. I don't know.

**Comment by dslawek** [comment]
I would try it [patch](https://github.com/dslawek/DCSFlightpanels/commit/3d1c2ea60abdbfcdcad5d6b1f375749277656159#diff-0e570ca6fabe24f94e52c1833f3ffd25567022beb826fa16891f3322051bc221)

**Comment by jdahlblom** [comment]
Check 4.4.30. Good luck setting the presets.

**Comment by dslawek** [comment]
It works 1:1. Thx!
