### ISSUE TITLE
Changes in the duplicated line are also applied to the parent line.

### ISSUE THREAD

**Issue by Saylors** [jdahlblom/DCSFlightpanels#150]
Hi!
1. I copy (duplicate) the string.
2. I make changes in the duplicate.
3. Changes in the duplicated line are also applied to the parent line.
Does not depend on the type of the selected command or plane (DCSFlightpanels_x64_4.4.30)
![Chassis Lever_1](https://user-images.githubusercontent.com/50142231/135097177-67121da5-766c-4811-ad62-48cbab8b9940.PNG)
![Chassis Lever_2](https://user-images.githubusercontent.com/50142231/135097201-08fa19c2-0acf-48be-be03-01dea1d25d53.PNG)
![Chassis Lever_3](https://user-images.githubusercontent.com/50142231/135097221-a6ffb6ba-7ad7-4f09-a95b-1b110963d3c3.PNG)
![Chassis Lever_4](https://user-images.githubusercontent.com/50142231/135097249-118c732f-b8c2-4b7b-b7b2-ca5e4b5bc758.PNG)

**Comment by jdahlblom** [comment]
I'll fix it.

**Comment by jdahlblom** [comment]
Check 4.4.30.

**Comment by Saylors** [comment]
Checked it, it works fine on 4.4.31. Thank you!
