### ISSUE TITLE
Integer numbers presented as floating point numbers in LCD screens of PZ69 when using Generic Radio Panel.

### ISSUE THREAD

**Issue by opatolinna** [jdahlblom/DCSFlightpanels#173]
Discussed about this minor issue in DCSFlightpanels Discord-channel on 2021.11.28.

So I'm trying to make a configuration for L-39 plane currently. I'd like to see pre-selected radio channel display of L-39 in one of the screens of PZ69. I have bound the LCD Data screen to variable _FRONT_RADIO_CHN_DISPLAY_, but it's shown in floating point number (e.g. "3.0000" instead of "3"). I have also tried for example formula like: _truncate(FRONT_RADIO_CHN_DISPLAY)_, but it doesn't change anything.

I investigated L-39ZA.lua and there is this code line 725:
_defineIntegerFromGetter("FRONT_RADIO_CHN_DISPLAY", getRadioPresetChan_FRONT, 99, "Readings", "FRONT Radio Preset Channel Display")_
To me it looks like DCSFlightpanels wants to get the data in integer format from DCS-BIOS, but for some reason forwards it in floating point format to Logitech PZ69?

**Comment by jdahlblom** [comment]
Yeah, we made changes throughout DCSFP to handle values as doubles. A bit tricky with DCS-BIOS values that are by default uint and then having the option of formulas which offers double.
I will check this out and make a new option of limiting the decimal places.

**Comment by opatolinna** [comment]
Thanks!
Just throwing an idea: add a checkbox next to formula with e.g. a label "treat data in integer format". So that users could choose how to display it. The data in double format could be then cast to integer format (or not - depending of the setting).

**Comment by jdahlblom** [comment]
![decimals](https://user-images.githubusercontent.com/10453261/144051072-9875fab2-fb58-49c9-85c4-c10dc6a89132.png)

So this is what I ended up with. You can choose there the amount of decimals needed. If you want to show the channel or the frequency, both will display properly now. Test latest release and see, thanks.

**Comment by jdahlblom** [comment]
Have you had a chance to test it?

**Comment by opatolinna** [comment]
Thank you @jdahlblom , now I got a chance to test this. Decimals feature seems to work.

One observation though - if you want to polish the feature: 
This decimals feature aligns numbers to the left side of the screens, while every other presets (like Mi-8, Mig-21 etc.) align numbers to the right side of the screens. Just a style thing, but in my opinion it would give a nice and consistent touch to the software.

**Comment by jdahlblom** [comment]
Good suggestion. We will look into it. We are doing some heavy refactoring right now so we will check it. Leave this issue open so we won't forget.

**Comment by opatolinna** [comment]
That's awesome, thank you! :)
