### ISSUE TITLE
StreamDeck XL key press sequence lost in UI

### ISSUE THREAD

**Issue by jwvanderbeck** [jdahlblom/DCSFlightpanels#187]
Steps to repro:
1. Create a new Key Press button action
2. In the Key Sequences window create one or more sequences
5. reopen the Key Sequences window and observe no entries

The key press binding sill shows in the main window and pressing the button on the Stream Deck still fires the key press as expected
[dcsfp_profile.zip](https://github.com/DCSFlightpanels

https://user-images.githubusercontent.com/161126/153693206-b80b7850-2986-4ac1-bc0a-4bbaf4276f35.mp4

/DCSFlightpanels/files/8052553/dcsfp_profile.zip)

**Comment by jdahlblom** [comment]
That single key press is not a sequence. If you add a minimum of 2 key presses you will see that they are shown. It is the same for the Saitek panels, if you add only one key press in the key sequence window it will be treated as a single key press, not a sequence.

**Comment by jwvanderbeck** [comment]
Well if that is intended then fine but it is non-inuitive.  I expected to see it in there and be able to see/modify the settings on that one key.
