### ISSUE TITLE
Massive performance hit - DCSFlightpanels_x64_4.6.8086.4

### ISSUE THREAD

**Issue by ZoeESummers** [jdahlblom/DCSFlightpanels#195]
Why is just a basic profile using over 13% of my CPU and 0.2% of my GPU when nothing is happening and no game is loaded? 

At times - when nothing is happening on the PC it peaks at over 17%!

![DCSFP_Usage](https://user-images.githubusercontent.com/2620349/161597639-1a614a97-1645-4018-b6c3-8b2f8fb7beb0.JPG)

**Comment by jdahlblom** [comment]
It is the loop where the UDP socket checks for/gets DCS-BIOS data. Also the HID library takes CPU when idle.

**Comment by ZoeESummers** [comment]
Does it need to poll so much? It’s not like a joystick with continuous movements needing latency free tracking. It’s an infrequently used keyboard emulator at the end of the day. Perhaps a manual setting to set the polling rate? I’m in vr on a 1080ti & 8700k cpu; I need all the cycles I can get.

**Comment by jdahlblom** [comment]
I've added a millisecond sleep to the poll which halfed the CPU hit. It may be that it needs some async tasking to get rid of that busy-waiting. Have to check that at some point. The HID library though I can't do anything with, there too it is polling for USB reports I'm guessing.

**Comment by ZoeESummers** [comment]
Sure, the system will have been built to handle and schedule hid polling. That’s not the concern. That will have been significantly optimised. I think doing this asynchronously is the way to go, but I know from experience that it’s complicated, a PITA to debug and not a quick job.

**Comment by ZoeESummers** [comment]
> I've added a millisecond sleep to the poll which halfed the CPU hit. It may be that it needs some async tasking to get rid of that busy-waiting. Have to check that at some point. The HID library though I can't do anything with, there too it is polling for USB reports I'm guessing.

When will this be pushed to mainline?

**Comment by jdahlblom** [comment]
Today maybe.

**Comment by jdahlblom** [comment]
Check 4.6.8186.

**Comment by ZoeESummers** [comment]
Latest update dropped it to 'Low' and I got 4fps back. Thanks so much! I'll happily close.
