### ISSUE TITLE
Copy Context Menu's SubMenu pointless?

### ISSUE THREAD

**Issue by ZoeESummers** [jdahlblom/DCSFlightpanels#196]
Why do we need a sub-menu on the Copy Command context menu to copy a DCS-BIOS configuration in order to paste it into another slot? Why isn't just 'Copy' enough of a command?

**Comment by jdahlblom** [comment]
Multiple items may be configured for a single button. Therefore the submenu is used. Although it could be done so that if the button only has one configuration then there is only "Copy".

**Comment by ZoeESummers** [comment]
Perhaps only display the sub menu in that specific use case. Where I have a single dcs-bios setting per control, the sub menu is an inconvenience.

**Comment by jdahlblom** [comment]
Check 4.6.8186.

**Comment by jdahlblom** [comment]
Close this if not relevant anymore.

**Comment by ZoeESummers** [comment]
Brilliant. Much quicker now. Thanks!
