### ISSUE TITLE
Can't copy between one panel config to paste into another.

### ISSUE THREAD

**Issue by ZoeESummers** [jdahlblom/DCSFlightpanels#197]
I have the PZ70.

I have different key bindings set when it's on ALT and other settings when it's on CRS.

I copy a key binding sequence from a button when in ALT and try to paste into a blank button on CRS mode and there is no paste option.

**Comment by jdahlblom** [comment]
I have fixed this. Will be in next release.

**Comment by jdahlblom** [comment]
Check 4.6.8186.

**Comment by jdahlblom** [comment]
Close this if not relevant anymore.

**Comment by ZoeESummers** [comment]
Works great. Thanks!
