### ISSUE TITLE
Only Key Emulation Module

### ISSUE THREAD

**Issue by Flyingfrog1** [jdahlblom/DCSFlightpanels#198]
Hello,

I built a new PC and had to reinstall DCS, DCS-BIOS and DSCFP.  The issue I get is I only have Key Emulation in the module drop down list.

DCS Open Beta
DCS-BIOS 0.7.44
DCSFP 4.6.8117.1 (with json setting point to DCS Open Beta saved file folder)

Can you help please?

Thank you

**Comment by jdahlblom** [comment]
I'm guessing DCSFP doesn't find the DCS-BIOS files. Go to settings and point DCS-BIOS to the correct folder.

**Comment by Flyingfrog1** [comment]
Is your guess right?  Here's where it point to my user path:   ...\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\doc

I get the green message "JSON files found in folder"

**Comment by jdahlblom** [comment]
Then it's something else. I can't figure it out right now.

**Comment by ZoeESummers** [comment]
Have you tried deleting and reinstalling dcs-bios in case of a corrupted download?

**Comment by Flyingfrog1** [comment]
Yes, I redownload and reinstalled.
