### ISSUE TITLE
Removing a panel from pc, the profile doesn’t adjust 

### ISSUE THREAD

**Issue by ZoeESummers** [jdahlblom/DCSFlightpanels#200]
I have 4 panels. One of the continually causes my pc to disconnect itself and another panel when dcs loads into a module. To solve this I’ve unplugged the no longer required panel. However all my previous profiles for all my modules were created when that panel was connected. Now on profile load I get a warning about a missing panel. Even if I make a change and resave then profile, it never ‘forgets’ about the old panel.

the panel causing the problems is the radio panel.

**Comment by jdahlblom** [comment]
I suggest you manually erase the configuration from the profile.

**Comment by ZoeESummers** [comment]
I never configured the radio panel buttons; it’s too complicated and I can’t use it for what I wanted as dcsflightpanels keeps trying to force me into radio mode and not allowing me to use the pots to control the crs & hdg knobs as I only wanted. 

Do you mean hack the profile file in notepad++? If so, I’ll try it but the user shouldn’t have to do that surely, there should be a cleaner way.

**Comment by jdahlblom** [comment]
Yes, with NP++. It is easy peasy stuff, a lot of users edit their profiles. Just delete the radio section. I will check this though if it is an easy fix. Won't promise anything though.
