### ISSUE TITLE
Any chance to add Virpil Panels so we can use just one program to manage different panels?

### ISSUE THREAD

**Issue by Sonny-Crockett** [jdahlblom/DCSFlightpanels#205]
https://github.com/charliefoxtwo/ViLA

https://github.com/Nereid42/VLEDCONTROL

**Comment by Sonny-Crockett** [comment]
These are some existing community written projects that effect status lights. etc.

**Comment by jdahlblom** [comment]
Hi,
it "should" be possible but the problem is getting the hardware. Generally we do not want to purchase hardware.

**Comment by Sonny-Crockett** [comment]
Would you only need one VPC device or each kind to make it compatible?

I could try to find something used and mail it.

**Comment by jdahlblom** [comment]
Would need one of each model to be sure the code works. But I am not familiar with these at all, how the various models differ etc. And there are two of us developing so. That is the problem.
