### ISSUE TITLE
Switching profiles causes cast error

### ISSUE THREAD

**Issue by jdahlblom** [jdahlblom/DCSFlightpanels#218]
1. Start DCSFP and open a profile for airplane A
2. Open another profile B
3. Manipulate the radio

There is an casting error when it tries to cast the _RadioPanelKnobA_ to _RadioPanelKnobB_.
Somehow there is a reference to the original _RadioPanelKnobA_ when in fact it should have been destroyed when switching profile.

```Error|System.InvalidCastException: Unable to cast object of type 'NonVisuals.Radios.Knobs.RadioPanelKnobA10C' to type 'NonVisuals.Radios.Knobs.RadioPanelKnobSpitfireLFMkIX'.|Unable to cast object of type 'NonVisuals.Radios.Knobs.RadioPanelKnobA10C' to type 'NonVisuals.Radios.Knobs.RadioPanelKnobSpitfireLFMkIX'.    at DCSFlightpanels.Radios.PreProgrammed.RadioPanelPZ69UserControlSpitfireLFMkIX.SetGraphicsState(HashSet`1 knobs) in C:\dev\GitHub\DCSFlightpanels\Source\DCSFlightpanels\Radios\PreProgrammed\RadioPanelPZ69UserControlSpitfireLFMkIX.xaml.cs:line 106```

**Comment by jdahlblom** [comment]
Could be the radio base class causing this.

**Comment by jdahlblom** [comment]
The fix was to clear the list of radio knobs in the base class SaitekPanel's Dispose().

**Comment by Saylors** [comment]
> 

Thank you so much.
