### ISSUE TITLE
Delegate to an instance method cannot have null 'this'

### ISSUE THREAD

**Issue by emcek** [jdahlblom/DCSFlightpanels#23]
Open any profile with wrong IDs, hit OK buttons and close profile.
```
11.11.2018 07:19:11  version : 1.0.104.5289
471072 Custom message = []
System.ArgumentException
Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at NonVisuals.ProfileHandler.Detach(SaitekPanel saitekPanel)
   at DCSFlightpanels.MainWindow.CloseTabItems()
```

**Comment by jdahlblom** [comment]
OK, do you mean USB PanelInstanceID?

**Comment by emcek** [comment]
yes

**Comment by jdahlblom** [comment]
1 Edit existing ID to something not correct
2 Open profile in DCSFP
3 An error dialog is displayed informing about this.
4 Click OK, close the dialog
5 Go to menu and choose "Close Profile"

Doing this does not produce any error for me. Is that the correct way to reproduce the problem? Am I doing something wrong?
