### ISSUE TITLE
Multiple functions on one switch not working anymore

### ISSUE THREAD

**Issue by Jakes-86** [jdahlblom/DCSFlightpanels#269]
Hi there.
Seem to be having issues assigning multiple functions to a single switch.
It seems to only trigger the first item, and the rest just don't trigger. Just updated to the latest version yesterday.
Hope it's an easy fix.
![image](https://user-images.githubusercontent.com/87943090/210867539-1b8c1b2a-4a77-46e3-b38d-36ab53da8eee.png)

**Comment by jdahlblom** [comment]
I have missed this issue, should have fixed it earlier. Seems to be something fishy going on. Examining it further.

**Comment by jdahlblom** [comment]
Fixed the problem and will be released asap. We need to test some more.

**Comment by Jakes-86** [comment]
Thanks so much!!! And apologies for only responding now, spam ate the notifications mails on my side

**Comment by jdahlblom** [comment]
If problem is solved in latest release then you can close this issue.

**Comment by Jakes-86** [comment]
Thanks so much for the fix. It is working perfectly now!
