### ISSUE TITLE
Key logging error?

### ISSUE THREAD

**Issue by Archie78818** [jdahlblom/DCSFlightpanels#275]
Just something i've noticed with the latest versions is when pressing both ALT keys for inputs the software seems to be adding an additional "control" input, a relatively minor issue I'm sure but it's there, thank you

![2023-01-21](https://user-images.githubusercontent.com/123276823/213894115-a6deb3c8-7a9d-4464-a0d0-8da2d433a578.png)

**Comment by jdahlblom** [comment]
Something to do with Windows. When saved the control part is removed. 
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Binding-keys-Alt-&-AltGr
