### ISSUE TITLE
Mosquito Fuel Transfer Cock Stream Deck Decoder Problem

### ISSUE THREAD

**Issue by No1sonuk** [jdahlblom/DCSFlightpanels#290]
Hi.
I get an error when trying to use the DCS-BIOS decoder for the Stream Deck buttons with the Mosquito's Fuel Transfer Cock.
The switch name is "TRANSFER_COCK-OUT".  The error message reads "The variable "transfercock" used is not defined."
I've not had any problems with other similar decoders.
![transfer_cock_error](https://user-images.githubusercontent.com/23527749/218328354-13d5034a-760d-457a-ae8c-e49cb6ed79bb.png)

**Comment by WarLord211** [comment]
Maybe its the Name TRANSFER_COCK-OUT it should be TRANSFER_COCK_OUT. 
I dont know if thats the problem but i fixed the lua in BIOS. its a Typo of mine.
Its uploaded to Master branch. (start flight before testing)

**Comment by No1sonuk** [comment]
Confirmed fixed.  Thanks.
