### ISSUE TITLE
Problem opening old profiles with new version

### ISSUE THREAD

**Issue by No1sonuk** [jdahlblom/DCSFlightpanels#306]
I get an error "Failed to determine aircraft ID (20) in your bindings file." when trying to open an F18 profile created with an old version of DCSFP.
The number changes when I try to load my two others.

**Comment by jdahlblom** [comment]
Please post the F-18C profile(s) here. Any additional information?
Post the version number of the old DCSFP you are using.
Post your error log here.

**Comment by No1sonuk** [comment]
Version it was written in: DCSFlightpanels_x64_4.6.8402.1

I think it would be better to use the Mosquito one I made as it uses no images, but still gives the same error.
Added as a zip

Error log extract:

2023-03-30 21:17:40.6392|Error|Failed to determine aircraft ID (45) in your bindings file.|

2023-03-30 21:17:40.6392|Error|System.Exception: Failed to determine aircraft ID (45) in your bindings file.|Failed to determine aircraft ID (45) in your bindings file.    at ClassLibraryCommon.DCSAircraft.LogErrorAndThrowException(String message)
   at ClassLibraryCommon.DCSAircraft.GetAircraft(Int32 id)
   at DCSFlightpanels.ProfileHandler.LoadProfile(String filename)


[dcsfp_Mosquito_profile.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/11115825/dcsfp_Mosquito_profile.zip)

**Comment by jdahlblom** [comment]
I could open your profile just fine. I think the reason is bios.lua. Because that is where all the profile IDs (numbers) are stored. Open your bios.lua and make sure you can see them there.
Also double check that you have the json path setting correct.
Uploading the bios.lua.
For example:
```dofile(lfs.writedir()..[[Scripts\DCS-BIOS\lib\FA-18C_hornet.lua]]) -- ID = 20, ProperName = F/A-18C Hornet```
[bios_lua.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/11118719/bios_lua.zip)

**Comment by jdahlblom** [comment]
You haven't by mistake installed from the old DCS-BIOS repository which isn't maintained anymore?

**Comment by No1sonuk** [comment]
No. This machine has only had Flightpanels installed.It's Open Beta if that's relevant. 
-------- Original message --------From: Jerker Dahlblom ***@***.***> Date: 31/03/2023  07:19  (GMT+00:00) To: DCSFlightpanels/DCSFlightpanels ***@***.***> Cc: No1sonuk ***@***.***>, Author ***@***.***> Subject: Re: [DCSFlightpanels/DCSFlightpanels] Problem opening old profiles with new version (Issue #306) 
You haven't by mistake installed from the old DCS-BIOS repository which isn't maintained anymore?

**Comment by No1sonuk** [comment]
I just checked and my BIOS.lua is the same as yours.

**Comment by jdahlblom** [comment]
So does your BIOS.lua contain the ID which is listed in the error message?

**Comment by No1sonuk** [comment]
I found the problem.
When I updated, I didn't change the settings to point to the correct JSON folder.
All working now
