### ISSUE TITLE
Dumb arse guide 

### ISSUE THREAD

**Issue by Snakebiteuk** [jdahlblom/DCSFlightpanels#313]
The dumb arse being me.

So a dumb arse basic guide more than the readme would be appreciated. 
I will then at some point replicate what I learn for other troubled interested parties :) 

Can someone guide me past the unpack point to how I start the integration or program.
Stupidly I expected an .exe but can see one.

Trying to use this for a logitech flight radio in dcs and star citizen.

After I activate and locate the console prog I can manage config but can't work out how I start the program for this.

Maybe I'm just not good at this part.
Help.

Thanks.

**Comment by jdahlblom** [comment]
If you don't have an exe then you clicked the wrong link. There are links to download the source code and also for the release (exe).

**Comment by Snakebiteuk** [comment]
Sound like a mistake I may have made thank you.
