### ISSUE TITLE
PID Streamdeck XL changed

### ISSUE THREAD

**Issue by Speed7rip** [jdahlblom/DCSFlightpanels#321]
Hello,
i was told to start an issue here. I simply found out, that the PID of an actual Elgate Streamdeck XL isn't 0x006c anymore. VID still fits but the PID of my streamdeck is 0x008f. What can i do now, to make DCSFP recognize my Device?
![image](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/133090845/34170c82-9b11-40f1-8529-69461e6889a0)

**Comment by jdahlblom** [comment]
We will have to add it to DCSFP. I will investigate and verify.

**Comment by Speed7rip** [comment]
Thank you

**Comment by jdahlblom** [comment]
Verified from other source: https://github.com/bitfocus/companion/issues/2113.
Can't find it in USB VID PID databases (yet).
Will add this.
