### ISSUE TITLE
Add PZ69 radio panel settings from Spitfire or P-47D for MosquitoFBMkVI.

### ISSUE THREAD

**Issue by Saylors** [jdahlblom/DCSFlightpanels#324]
The simple 4-channel A/B/C/D radio on the MosquitoFBMkVI can be replaced by advanced settings like the Spitfire or P-47D (radios are the same).
I made 4 new screenshots of the radio for the MosquitoFBMkVI - select the appropriate one and replace the old one, please (the one from the P-51 is installed now). Dark screenshots look much better)
![Screen_230511_175602](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/052ef222-c02e-4a59-8b52-1e1acb85889e)
![Screen_230511_175612](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/aada3398-aa4a-4b8c-bfeb-770ae02e3607)
![Screen_230511_175618](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/526f2198-f70a-41fd-8a85-e317f5e99516)
![Screen_230511_180613](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/800deb52-008e-48e7-b487-11fb97a4b993)

**Comment by jdahlblom** [comment]
OK thanks, will do.

**Comment by jdahlblom** [comment]
Was this fixed already?

**Comment by Saylors** [comment]
![Снимок экрана 2023-07-14 173038](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/cce83914-09e1-48ce-a50f-59760f77c100)
No, it's not fixed.

**Comment by jdahlblom** [comment]
Alright, new release will have this look:
![2023-07-14_181409](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/10453261/1b6b29e9-c2de-4e75-82e7-5d0cdd17bfbd)

**Comment by Saylors** [comment]
On P-47 it is possible to switch the radio backlight and the transmit/receive lever in the cockpit in the dark. Is it possible to do the same on Moskito? The BIOS commands are slightly different for these airplanes.
![0](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/7121736b-7840-44a1-8bf6-b8207e8bf636)
![1](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/2440aa6a-d476-46fe-9927-ec00d1e28acb)
![2](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/c31a9e57-49e7-4139-b91e-2e2d82fee7e5)
![3](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/9d390d86-5705-4bc0-a8b8-80acb3fa045e)
![4](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/66426672-e2ec-4c33-b1b8-6e747148b286)
![5](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/206d23ff-935e-466e-a44a-1e873256e038)

**Comment by jdahlblom** [comment]
Check latest pre-release.

**Comment by Saylors** [comment]
Yay! It's working perfectly! Especially liked the volume setting.
![Снимок экрана 2023-07-15 220934](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/50142231/f0d40339-5a27-457a-8354-cd56aa679f78)

**Comment by Saylors** [comment]
Thank you!

**Comment by jdahlblom** [comment]
Is it only Spitfire and P-47D that have this radio model? I was thinking of checking that all work the same.

**Comment by Saylors** [comment]
Yes, that's right, the P-51, P-47D, Spitfire and the Mosquito have this radio - these four WWII airplanes have the same radio.  
1. The P-51 needs to finalize the radio control and make it like the Mosquito (especially the volume).
2. On P-47D add only volume control (ACT/STBY + Small Dial : Volume), as it is now on Mosquito.
3. On the Spitfire module there is no volume control for the radio - so leave it as it is.
- And then the P-51, P-47D, Spitfire and the Mosquito will all have the same radio controls.

**Comment by jdahlblom** [comment]
Check latest pre-release.

**Comment by Saylors** [comment]
On the P-51, P-47D, Spitfire and the Mosquito, the radio controls work perfectly and identically! Thank you so much for your help!
