### ISSUE TITLE
Streamdeck - Button copy/paste between different panels

### ISSUE THREAD

**Issue by Mutex666** [jdahlblom/DCSFlightpanels#330]
During my tests of SD+, I tried to copy paste button from one pannel to another. The copy is working fine but for some reason, 
DCSFP think that there is still a dirty listener on the origin panel.

Example : 
- Panel 1, button 2 'copy'
- Panel 2, button 4 'Paste' => ok , everything is copied
- Panel 1, trying to select another button => "Discard Changes to button 2 ?" message 

Looks like during the copy something is wrong with the event listeners queried in `public static bool AreThereDirtyListeners(objectsender)`

I think after the copy the button should be set a flag 'dirty' & attached some event somehow

Don't know if it's only due to my SD+ implementation but I have (currently) no other already implemented streamdeck to test it.

**Comment by jdahlblom** [comment]
OK so the logic is meant for when a user configures Button A but does not save ("Accept changes"), instead clicks an other button.
It doesn't work with how copying and pasting works *except* if you save immediately after paste you don't get this error.

**Comment by jdahlblom** [comment]
I removed the code, if user is editing a single button and then clicks a different button the changes will be lost. The GUI is a maze / labyrinth and I don't have the energy to go finding a good solution.
