### ISSUE TITLE
DCS-BIOS Control Reference unsupported on latest Chrome

### ISSUE THREAD

**Issue by TheBlueRuby** [jdahlblom/DCSFlightpanels#332]
Upon trying to open the control reference app (step 7 of the install guide), chrome refuses to open it, saying that chrome apps are deprecated.

**Comment by jdahlblom** [comment]
Where is this guide?

https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/DCS-BIOS-Control-Reference-Page

**Comment by TheBlueRuby** [comment]
Sorry, should have specified it as the DCS-BIOS one. Some of the guides are updated but others are still stuck on the old chrome app-based version.

**Comment by jdahlblom** [comment]
Did you get it working with dcs-bios or Bort?

**Comment by TheBlueRuby** [comment]
I found an electron based version that someone made, but have been putting
dcs-bios stuff on hold as I am building a better stick
