### ISSUE TITLE
Stream Deck Mini

### ISSUE THREAD

**Issue by Gebirgsjaeger** [jdahlblom/DCSFlightpanels#353]
I have a problem with my new Stream Deck Mini.
The HID and the VID from the new Deck has changed from "0063" to "0090". So DCSFP can not find the StreamDeck.
![Screenshot_2023-06-17_101018](https://github.com/DCSFlightpanels/DCSFlightpanels/assets/140961207/5636e0ed-ba51-4ccc-871f-66191f2ac4cf)

**Comment by jdahlblom** [comment]
I will verify the information and add that PID to DCSFP. Thanks.
