### ISSUE TITLE
Layer Navigation

### ISSUE THREAD

**Issue by Kegzie73** [jdahlblom/DCSFlightpanels#389]
Hi, just setting up a panel in stream deck. Having an issue when I navigate from one layer to the next it selects the toggle on the next layer. Example below when I navigate from UFC_Main it loads the UFC_Actions layer and selects the toggle on the 1 button also which keeps it in state = 1

![image](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/146910690/65688077-87f5-4000-962b-0bd08672bccd)

**Comment by jdahlblom** [comment]
Please upload your bindings file too. Just drag & drop into the comment field.

**Comment by Kegzie73** [comment]
Attached binding :)

[dcsfp_profile_Toggle.zip](https://github.com/DCS-Skunkworks/DCSFlightpanels/files/12882247/dcsfp_profile_Toggle.zip)

**Comment by jdahlblom** [comment]
OK, I can see the problem. When pressing to switch layer it switches layer but when releasing the button is executes the ```release``` command on that layer for that button. I will investigate.

**Comment by jdahlblom** [comment]
Try this one : https://github.com/DCS-Skunkworks/DCSFlightpanels/releases/tag/v4.10.2

**Comment by Kegzie73** [comment]
All good, works fine now! Cheers!
