### ISSUE TITLE
F18 Launch Bar No Toggle Input

### ISSUE THREAD

**Issue by Kegzie73** [jdahlblom/DCSFlightpanels#391]
Hi,

Setting up a switch for the launch bar and there is no option for a TOGGLE only SET_STATE. Could a TOGGLE input be added?

![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/146910690/37177d7b-6b81-4f63-a561-8bdf622d8bf6)

Cheers

Pat

**Comment by charliefoxtwo** [comment]
Line in question:
https://github.com/DCS-Skunkworks/dcs-bios/blob/594e2f5abd508ad86b10caa38d11e19460228e33/Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua#L638-L638

I'll see if we can change this to defineToggleSwitch or similar.

**Comment by jdahlblom** [comment]
@Kegzie73 
```
Press = SET_STATE 1 
Release = SET_STATE 0 
```
Wouldn't that work?

**Comment by Kegzie73** [comment]
Ill try tonight but pretty sure this will set back to 0 once release i.e.) the hook will go down on press (1) and then on releasing (0) it will retract again.

**Comment by charliefoxtwo** [comment]
BIOS has a toggle input for this control (tested and it works). Migrating to the flightpanels repo as this seems be a flightpanels issue.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/30303272/df632886-14d9-425a-86c0-81bafe1bd1f8)

**Comment by jdahlblom** [comment]
![2023-10-13_094854](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/10453261/9c83b569-71c3-42bb-b87c-dd7a64926493)

If you update DCSFP and dcs-bios I think it will work. Can't say what caused that or what fix changed the behavior.

**Comment by Kegzie73** [comment]
Cheers mate, will have a crack at it and let you know how I go

**Comment by Kegzie73** [comment]
Just tested it, spot on works great! Thanks!
