### ISSUE TITLE
StreamDeck Button Image not be displayed correctly

### ISSUE THREAD

**Issue by XtyeJiang** [jdahlblom/DCSFlightpanels#401]
Thank you for your outstanding work, This makes the world more beautiful and saves my StreamDeck by the way. XD
I found that the latest update resolves the "intrger" value issue, which allows StreamDeck to use conditional formatting, but the DCS-BIOS Control Type is not displayed by StreamDeck regardless of whether it is set to "intrger" or "String". Even if the button Image is not set to "DCS-BIOS Recoder" and only "Static Text" is used, the StreamDeck will blink once each time the input is entered (the flashing will show the correct content, but the screen will immediately go black).
Image------has been Accept Changes

![Screenshot 2023-10-19 000305](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/d01c9a5a-7316-44c4-b3fa-d6303622722a)
![Screenshot 2023-10-19 001136](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/fd21d642-f8c4-46e4-ac48-a1724bf1d279)

**Comment by jdahlblom** [comment]
Could you write down a step by step list on how I can reproduce this.
Not really clear to me at this point what the actual problem is.

**Comment by XtyeJiang** [comment]
> Could you write down a step by step list on how I can reproduce this. Not really clear to me at this point what the actual problem is.

1. DCS JF-17 Thunder free flight
2. File - New - Choose Module - JF-17 Thunder - OK 
3. Select a button
4. "Button Image" area select DCS-BIOS Decoder
5. "Button Image" Add/Edit Button
6. "DCS-BIOS Control Type" Select "String"
7. "Press space for list" Select any item - OK
![Screenshot 2023-10-19 195644](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/766c0e44-4c8f-4157-b05f-b8bbed8b20be)
8.  Main screen - Accept Changes
![Screenshot 2023-10-19 195253](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/aa241579-bbba-4b2a-87b4-c8b678c8245c)
Main-Windows button "1"  show white block, but StreamDeck have no display content.
![Screenshot 2023-10-19 195928](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/ee438a69-441c-49a8-a137-2207b47517e7)

**Comment by jdahlblom** [comment]
OK, thanks. I will look into this asap.

**Comment by jdahlblom** [comment]
I think you forgot to choose either ```Rule Formatting``` or ```Raw DCS-BIOS value``` for the button. (and in this case the choice ```Raw DCS-BIOS value``` is the only valid one since it isn't an number) 

```BUG =>``` I noticed that the ```OK``` button was enabled even when neither of the two choices were selected. 
You have to click the blue link below the textbox to insert the keyword ```{dcsbios}```. You type your own text there too either above or below.
I have fixed the ```OK``` button bug but you can just follow the advice here and you will be fine. I will release this later.
Did this help you?

![2023-10-20_164042](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/10453261/681ee39c-50b0-4c4e-99c7-7f35315edb87)

**Comment by XtyeJiang** [comment]
It works.
Thank you, JDAHLblom.
I think I asked a foolish question and I'm sorry for taking up your time.
My best regards.

**Comment by jdahlblom** [comment]
Question was not foolish at all, good luck.
