### ISSUE TITLE
minimize taskbar issues with x64_4.11.0 

### ISSUE THREAD

**Issue by marcocom** [jdahlblom/DCSFlightpanels#432]
OS: Windows 11
App, if set to 'minimize to taskbar' now opens and disappears without taskbar icon and no way to bring up the UI.  dcsfp.exe task still runs fine in background. This cannot be recovered without wiping config files in \AppData\Local\DCSFlightpanels_(DCSFP) which brings back the app

issue reproduces once setting is toggle on again.

**Comment by jdahlblom** [comment]
Closing this now. Reopen if you still have problems.
