### ISSUE TITLE
Error, control UHF RADIO does not exist.

### ISSUE THREAD

**Issue by Flyingfrog1** [jdahlblom/DCSFlightpanels#456]
Hello,

Is it normal having the error message "Error, control UHF RADIO does not exist. (<module name>)" when create or open profile for AH-64 Apache and F-16C Viper?

DCS open beta
DCS-BIOS Fork 0.7.45
DCSFlightpanels 4.11.3
Modules AH-64 Apache and F-16C Viper

Regards

**Comment by jdahlblom** [comment]
I know the error you mention, for some reason I can't trigger it with the latest release.

**Comment by Flyingfrog1** [comment]
I just removed DCSFlightpanels_x64_4.11.3 and installed DCSFlightpanels_x64_4.11.7, same result. I'll try be re-install DCS-BIOS

**Comment by Flyingfrog1** [comment]
Re-install DCS-BIOS Fork 0.7.45, same result

**Comment by jdahlblom** [comment]
Post the profile you are using.

**Comment by jdahlblom** [comment]
Update to [this](https://github.com/DCS-Skunkworks/dcs-bios/releases/tag/latest) version and see if the problem persists.

**Comment by Flyingfrog1** [comment]
Many thanks!!! That fixed the issue! Thank you very much for your help. :-)
