### ISSUE TITLE
error lua route

### ISSUE THREAD

**Issue by eggling** [jdahlblom/DCSFlightpanels#470]
![Screenshot 2024-02-09 101241](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/16866116/8cc2fb5b-7e81-4e19-ab85-1bdf61c83fbf)

this was fixed duplicating the lua files on the folder indicated

**Comment by jdahlblom** [comment]
Are you using both DCS official and openbeta?
Yes the version you use should have the dcs-bios files installed.

**Comment by jdahlblom** [comment]
If all is OK you can close this issue.
