### ISSUE TITLE
Works not with gazelle

### ISSUE THREAD

**Issue by Virusloading-99** [jdahlblom/DCSFlightpanels#471]
does not work properly with the gazelle. You cannot program the battery main switch or altimeter. But magnetic switches and trimmers work. It is strange. Do you have an idea? I just pulled the new update today. But I know that everything worked a while ago.

**Comment by jdahlblom** [comment]
Which DCS-BIOS controls are you using for battery and altimeter? If it has worked please post your profile where it worked. Are you using DCS-BIOS nightly build?

**Comment by jdahlblom** [comment]
I found a radio bug in SA342 AM Radio so download ```version 4.11.8```.

**Comment by Virusloading-99** [comment]
I tried 2 variants. 1. with INC and DEC 2nd with 1.2 I don't know much
about programming language, so I have to rewrite it like this.
Unfortunately, I no longer have my old profiles that worked. But I will try
again to download an older version of DCSFlightpanels. And if it works,
I'll let you know. In any case, it had worked for me before.

Jerker Dahlblom ***@***.***> schrieb am Sa., 10. Feb. 2024,
12:40:

**Comment by jdahlblom** [comment]
* download and use dcs-bios *nightly build*
* download dcsfp 4.11.8

**Comment by Virusloading-99** [comment]
Thanks, that worked. Good job and respect for the quick fix.
I'm closing the issue.
