### ISSUE TITLE
[BUG]FC3 can be exported to BIOSBuddy but cannot be displayed on DCSFP DCS-BISO Decoder

### ISSUE THREAD

**Issue by XtyeJiang** [jdahlblom/DCSFlightpanels#521]
**DCSFP version**
DCSFlightpanels_x64_4.11.12

**DCS-BIOS version**
DCS Unified 2.9.3
DCS-BIOS_0.8.0 ?

**Describe the bug**
I was using StreamDeck, and when I tried to get the engine RPM of FC3 module aircraft using DCSFP, I found that DCSFP's DCS-BIOS Decoder could not get this information, but the RPM was displayed normally in BIOSBuddy, I tried to fix this problem. But my poor programming knowledge makes it impossible for me to do that. Could you please take some time to verify this problem?

**Expected behavior**
Can the DCS-BIOS Decoder get data consistent with BIOSBuddy when using the FC3 module?

**Screenshots**
![1](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/a628dc37-7ab3-4a75-8156-39b514801ab6)

![2](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/54302601-c1c0-41ec-880d-138531f2e058)

**Comment by jdahlblom** [comment]
In the decoder window, select "String". Do they show then?

**Comment by XtyeJiang** [comment]
![Screenshot 2024-05-03 225214](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/28e86465-18dc-4701-98a6-3c66f2f5c052)
No more useful data.

**Comment by jdahlblom** [comment]
Ok, seems like there is a bug.

**Comment by jdahlblom** [comment]
[DCSFlightpanels_x64_4.11.12.zip](https://github.com/DCS-Skunkworks/DCSFlightpanels/files/15210161/DCSFlightpanels_x64_4.11.12.zip)

See if that works. I can't test myself at the moment but I did see new controls show up.

**Comment by XtyeJiang** [comment]
I tested it on DCS 3.9.4.53990(the latest version) 
It worked fine
Thank you bro!!
![Screenshot 2024-05-05 012020](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/147996281/b3913a0e-ed6f-4b3b-bf6a-cc2f3bc6d97d)

**Comment by jdahlblom** [comment]
Thanks, I'll make a new official release with this.

**Comment by jdahlblom** [comment]
Did the new version work properly?
